updated front and back
Simple2B/site pull request #70
Opened 2023-08-21 12:37 UTC by Nazar-kob

2023-08-21 15:29 UTC, StoliarskyiKostiantyn approved these changes

2023-08-21 15:29 UTC, StoliarskyiKostiantyn commented on front/src/components/Career/Apply.tsx
> +        <NavigateBtn title="Sign In to apply" pushTo="signin"></NavigateBtn>
for what change from selfclosing tag?

2023-08-21 15:29 UTC, StoliarskyiKostiantyn commented on front/src/components/Buttons/NavigateBtn.tsx
> +export interface INavigateBtn {
you will use it somewhere else?

2023-08-21 15:29 UTC, StoliarskyiKostiantyn commented on front/src/components/CaseCard/CaseCard.tsx
> +          src={card.previewImageUrl}
you rely on back?

2023-08-22 07:15 UTC, nixissmtp requested changes

2023-08-22 12:07 UTC, merged